# Generated by Django 2.2.2 on 2019-06-25 18:55

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.CharField(db_index=True, default=core.models.uuid_hex, editable=False, max_length=32, unique=True)),
                ('enable', models.BooleanField(default=True)),
                ('club_premier_id', models.CharField(blank=True, max_length=45, null=True, verbose_name='ID Club Premier')),
                ('accepts_terms', models.BooleanField(default=False, verbose_name='Terminos')),
                ('passwordToken', models.CharField(blank=True, default=core.models.uuid_hex, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.CharField(db_index=True, default=core.models.uuid_hex, editable=False, max_length=32, unique=True)),
                ('enable', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.CharField(db_index=True, default=core.models.uuid_hex, editable=False, max_length=32, unique=True)),
                ('enable', models.BooleanField(default=True)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('completed', models.BooleanField()),
                ('client_user_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ClientUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
