# Generated by Django 2.2.2 on 2019-06-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='passwordToken',
        ),
    ]
