# Generated by Django 2.2.2 on 2019-06-25 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_clientuser_passwordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='passwordToken',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
