# Generated by Django 2.2.2 on 2019-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_session_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='attempt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
