# Generated by Django 2.2.2 on 2019-07-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('users', '0005_session_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Game'),
        ),
    ]
