# Generated by Django 2.2.2 on 2019-07-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_session_high_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='high_bonus',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
