# Generated by Django 2.2.2 on 2019-07-16 18:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190709_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.CharField(db_index=True, default=core.models.uuid_hex, editable=False, max_length=32, unique=True)),
                ('enable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=125, verbose_name='Nombre del Archivo')),
                ('start_date', models.DateField(help_text='Fecha desde donde iniciara el reporte', verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(help_text='Fecha hasta donde llegara el reporte', verbose_name='Fecha de fin')),
                ('email', models.EmailField(max_length=254)),
                ('url', models.FileField(blank=True, help_text='Después de terminado el reporte se podra descargar desde esta URL', upload_to='report/punctuation/')),
                ('percent', models.SmallIntegerField(blank=True, default=0, verbose_name='Porcentaje Genera Total')),
                ('percent_report', models.SmallIntegerField(blank=True, default=0, verbose_name='Porcentaje Reporte')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
