# Generated by Django 2.2.2 on 2019-07-22 18:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_reportusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.CharField(db_index=True, default=core.models.uuid_hex, editable=False, max_length=32, unique=True)),
                ('enable', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='file/database')),
                ('percent', models.SmallIntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
