# Generated by Django 2.2.2 on 2019-07-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_updatefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='accumulation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Acumulación Premier'),
        ),
    ]
