# Generated by Django 2.2.2 on 2019-06-25 18:55

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.CharField(db_index=True, default=core.models.uuid_hex, editable=False, max_length=32, unique=True)),
                ('enable', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('total_levels', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.CharField(db_index=True, default=core.models.uuid_hex, editable=False, max_length=32, unique=True)),
                ('enable', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('game_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
